language: c
sudo: false

matrix:
  include:
  - os: osx
    compiler: clang
  - os: linux
    dist: "trusty"

install:
  - export PATH="`pwd`/build:${PATH}"
  - if [[ "$TRAVIS_OS_NAME" == "osx"  ]]; then rvm get stable; brew update && brew install python3 ninja pkg-config pcre2 portaudio; echo "done"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip && unzip -q ninja-linux.zip -d build; fi
  - pip3 install meson

script:
  - meson build --prefix="$PWD/install"
  - ninja -C build test install

addons:
  apt:
    packages:
    - pkg-config
    - python3
    - python3-pip
    - libasound2-dev

