language: c
sudo: false

matrix:
  include:
    - env: TASK="osx"
      os: osx
      compiler: clang
      before_install: rvm get stable
      install:
        - brew update
        - brew install python3 ninja pkg-config pcre2 portaudio
        - pip3 install meson
    - env: TASK="linux"
      os: linux
      dist: "trusty"
      install:
        - export PATH="`pwd`/build:${PATH}"
        - wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip && unzip -q ninja-linux.zip -d build
        - pip3 install meson
      addons: {apt: {packages: [libasound2-dev, python3-pip, pkg-config]}}

# We don't want to pull submodules recursively
git:
  submodules: false

before_install:
  - git submodule update --init

script:
  - meson build --prefix="$PWD/install"
  - ninja -C build test install

